[toolchain]
anchor_version = "0.29.0" # Add this
package_manager = "Yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_cnft = "91CLwQaCxutnTf8XafP3e6EmGBA3eUkMaw86Hgghax2L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
